name: Mirror to GitLab

on:
  push:
    branches:
      - 1.21.1
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/randomusert/gregtech-pack-core-gitlab-mirror.git
          git push --all --force gitlab